#!name = 飞猪广告拦截（每日自动更新）
#!desc = 自动同步自 fmz200 和 zirawell 两位作者的源文件
#!version = 2026.02.21
#!system = ios

[Rule]
# 自动提取于 2026-02-21 10:32:31
# 共 1 条规则

^https?:\/\/acs\.m\.taobao\.com\/gw\/mtop\.fliggy\.crm\.(?>popresource|screen) - reject

[MITM]
# MITM 主机名（自动提取自规则）
hostname = %APPEND% *.fliggy.com, *.alitrip.com, *.taobaotrip.com

# 确保 YouTube 等不受影响
skip-server = *.googlevideo.com, *.youtube.com, *.googleapis.com
